### ISSUE TITLE
About Access Token

### ISSUE THREAD

**Issue by youyi1314** [livechat/livechat-public-docs#862]
I got a few questions about access_token for both agent API and customer API
Because I using server side app, 
1. is it possible to create a long live customer API access_token for customer and agent?
2. is it possible to create a token without redirect?
3. I create a customer using agent API [Agent Create Customer](https://developers.livechat.com/docs/messaging/agent-chat-api/#create-customer), after that I using [Create a new customer API](https://developers.livechat.com/docs/authorization/authorizing-api-calls/#creating-a-new-customer)  to generate access_token with entity_id (customer id created from [Agent Create Customer](https://developers.livechat.com/docs/messaging/agent-chat-api/#create-customer)), but I use the access_token to call [Start Chat API](https://developers.livechat.com/docs/messaging/customer-chat-api/#start-chat) it show 
`{
	"error": {
		"type": "authentication",
		"message": "Invalid access token"
	}
}`

is it I missing something?

Thanks

**Comment by ale-kacperczyk** [comment]
Hi @youyi1314 👋🏻

1. No. The token’s lifetime for both agents and customers is 28800s, and it cannot be overwritten. To allow access after the token expires, use the refresh token: https://developers.livechat.com/docs/authorization/authorizing-api-calls/#using-the-refresh-token

2. In general, yes. You can create a Personal Access Token, which is assigned to the agent. However, this token will authorize calls only to the Agent Chat API and Configuration API, not the Customer Chat API. For production-ready applications, you need to implement the redirect. You can use [this tutorial](https://developers.livechat.com/docs/authorization/authorization-in-practice/#step-3-exchange-the-code-for-an-access-token) as your reference.

3. What you’re doing wrong is you’re trying to create a customer via the Agent Chat API instead of calling LiveChat Accounts. The method you’re using will create a new agent within a license, but you need to create a new entity. To do that, follow this tutorial: https://developers.livechat.com/docs/authorization/authorizing-api-calls/#creating-a-new-customer

I invite you to our [live coding session](https://developers.livechat.com/live-coding-authorizing-web-apps/) dedicated to **web app authorization**. It’ll take place **this Friday (March 19th)**. Even though you’re building a server-side app, the session could serve as a great foundation for your further development.
Also, I want to let you know that server-side app authorization is exactly what we’ll cover during our next live coding (the date is yet to be decided). If you don’t want to miss it, I recommend you join our [Discord for Developers](https://discord.gg/gRzwSaCxg4). It’s a place for sharing knowledge among other developers who build LiveChat integrations. There’s also the #ask-community channel where you can seek advice from other developers and ask your authorization-related questions if you have any more.

**Comment by youyi1314** [comment]
> Hi @youyi1314 👋🏻
> 
> 1. No. The token’s lifetime for both agents and customers is 28800s, and it cannot be overwritten. To allow access after the token expires, use the refresh token: https://developers.livechat.com/docs/authorization/authorizing-api-calls/#using-the-refresh-token
> 2. In general, yes. You can create a Personal Access Token, which is assigned to the agent. However, this token will authorize calls only to the Agent Chat API and Configuration API, not the Customer Chat API. For production-ready applications, you need to implement the redirect. You can use [this tutorial](https://developers.livechat.com/docs/authorization/authorization-in-practice/#step-3-exchange-the-code-for-an-access-token) as your reference.
> 3. What you’re doing wrong is you’re trying to create a customer via the Agent Chat API instead of calling LiveChat Accounts. The method you’re using will create a new agent within a license, but you need to create a new entity. To do that, follow this tutorial: https://developers.livechat.com/docs/authorization/authorizing-api-calls/#creating-a-new-customer
> 
> I invite you to our [live coding session](https://developers.livechat.com/live-coding-authorizing-web-apps/) dedicated to **web app authorization**. It’ll take place **this Friday (March 19th)**. Even though you’re building a server-side app, the session could serve as a great foundation for your further development.
> Also, I want to let you know that server-side app authorization is exactly what we’ll cover during our next live coding (the date is yet to be decided). If you don’t want to miss it, I recommend you join our [Discord for Developers](https://discord.gg/gRzwSaCxg4). It’s a place for sharing knowledge among other developers who build LiveChat integrations. There’s also the #ask-community channel where you can seek advice from other developers and ask your authorization-related questions if you have any more.

Hi,
Thanks for your replay and so detail for me,
I will join your discord, thanks for the invitation, 
for the live coding session, I would like to join, but the invitation [link ](https://developers.livechat.com/live-coding-authorizing-web-apps/) was expired, not sure why i can't join, and my email is youyi1314.kenny[AT]gmail.com, please send to my email?

Thanks again for the detail.

**Comment by ale-kacperczyk** [comment]
Hi @youyi1314,
The live coding will be hosted on Discord on March 19th, 2.p.m. CET. Make sure you join the server – we'll post all the details about the session there. You don't need to sign up anywhere for the session, joining Discord is enough. See you on Friday!

Discord: https://discord.com/invite/gRzwSaCxg4
